name: Test and Build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v4
       - uses: actions/setup-go@v5
       - name: Install dependencies
         run: go get .
       - name: Build
         run: make build
       - name: Test
         run: make test
